#!/bin/sh
[ "$ACTION" = "ifup" ] || [ "$ACTION" = "ifupdate" ] || exit 0
[ "$ACTION" = "ifupdate" ] && [ -z "$IFUPDATE_ADDRESSES" ] && [ -z "$IFUPDATE_DATA" ] && exit 0
[ -n "$INTERFACE" ] && [ "$INTERFACE" != "loopback" ] || exit 0

/usr/bin/ucode /usr/share/ucode/hnat/detect.uc
